In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('./images/flemingo.jpg')

In [3]:
b, g, r = cv2.split(img)
cv2.imshow('Blue', b)
cv2.imshow('Green', g)
cv2.imshow('Red', r)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
b

array([[188, 189, 189, ..., 188, 188, 188],
       [188, 189, 189, ..., 188, 188, 188],
       [188, 189, 189, ..., 188, 188, 188],
       ...,
       [167, 167, 167, ..., 177, 177, 177],
       [171, 171, 172, ..., 177, 177, 177],
       [177, 177, 178, ..., 177, 177, 177]], shape=(640, 640), dtype=uint8)

In [5]:
g

array([[163, 164, 164, ..., 163, 163, 163],
       [163, 164, 164, ..., 163, 163, 163],
       [163, 164, 164, ..., 163, 163, 163],
       ...,
       [134, 134, 134, ..., 144, 144, 144],
       [141, 141, 142, ..., 144, 144, 144],
       [147, 147, 148, ..., 144, 144, 144]], shape=(640, 640), dtype=uint8)

In [6]:
r

array([[119, 120, 120, ..., 119, 119, 119],
       [119, 120, 120, ..., 119, 119, 119],
       [119, 120, 120, ..., 119, 119, 119],
       ...,
       [ 88,  88,  88, ...,  98,  98,  98],
       [ 94,  94,  95, ...,  98,  98,  98],
       [100, 100, 101, ...,  98,  98,  98]], shape=(640, 640), dtype=uint8)

Converting the color

In [10]:
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [ ]:
cv2.imshow('RGB', img_rgb)
cv2.imshow('Grey', img_grey)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()