In [9]:
import numpy as np
import cv2

In [13]:
#change the color of an image using opencv
img = cv2.imread('./flemingo.jpg')

In [14]:
print(img)

[[[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 ...

 [[167 134  88]
  [167 134  88]
  [167 134  88]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[171 141  94]
  [171 141  94]
  [172 142  95]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[177 147 100]
  [177 147 100]
  [178 148 101]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]]


In [15]:
img.shape

(640, 640, 3)

In [16]:
b,g,r = cv2.split(img)

In [17]:
b

array([[188, 189, 189, ..., 188, 188, 188],
       [188, 189, 189, ..., 188, 188, 188],
       [188, 189, 189, ..., 188, 188, 188],
       ...,
       [167, 167, 167, ..., 177, 177, 177],
       [171, 171, 172, ..., 177, 177, 177],
       [177, 177, 178, ..., 177, 177, 177]], dtype=uint8)

In [19]:
cv2.imshow('original', img)
cv2.imshow('blue', b)
cv2.imshow('green', g)
cv2.imshow('red', r)
cv2.waitKey(0)
cv.destroyAllWindows()

NameError: name 'cv' is not defined

In [20]:
# changing the color

In [22]:
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [23]:
cv2.imshow('original', img)
cv2.imshow('RGB', img_rgb)
cv2.imshow('Gray', gray)
cv2.waitKey(0)
cv.destroyAllWindows()

NameError: name 'cv' is not defined

In [24]:
cv2.imwrite("grapy.png", gray)


True

In [25]:
cv2.imwrite("rgb.png", img_rgb)

True